### ISSUE TITLE
Beginner-Question: how to create traces in crm online?

### ISSUE THREAD

**Issue by bryce2071** [MscrmTools/MscrmTools.CrmTraceReader#1]
Hi, 

with this tool i can read traces, but how can i create traces in crm online?
Earlier, there was the crm diag tool, but i cant find this for download and even if i find the downlad - can i create traces with it for crm online?
If this tool is not able to do this, how can i trace then?
thx, Peter

**Comment by MscrmTools** [comment]
There is no trace for CRM Online like it exists for CRM OnPremise.

You can trace execution of plugins and workflow activities but not more
